In [38]:
import pandas as pd

In [39]:
df = pd.read_csv('../data/challenge_435.csv')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Season,City,Sport,Event,Medal,Games1,Games2
0,84,Sean Clark,M,26,165.0,55.0,Unitonaris,USA,2004 Summer,Summer,Athina,Wrestling,"Wrestling Men's Featherweight, Freestyle",Silver,2004,Summer
1,90,Simon Wilson,F,21,163.0,60.0,Rusfara,RUS,2004 Summer,Summer,Athina,Cycling,Cycling Women's Sprint,Silver,2004,Summer
2,165,Max Robertson,F,20,175.0,56.0,Unitonaris,USA,2004 Summer,Summer,Athina,Taekwondo,Taekwondo Women's Featherweight,Silver,2004,Summer
3,514,Anna Ince,M,29,191.0,84.0,Swedaris,SWE,2004 Summer,Summer,Athina,Wrestling,"Wrestling Men's Light-Heavyweight, Greco-Roman",Silver,2004,Summer
4,543,Nicholas Hart,M,25,198.0,89.0,Rusfara,RUS,2004 Summer,Summer,Athina,Volleyball,Volleyball Men's Volleyball,Bronze,2004,Summer

In [40]:
#assign point values per medal
df.loc[df['Medal'] == 'Gold', 'points'] = 3
df.loc[df['Medal'] == 'Silver', 'points'] = 2
df.loc[df['Medal'] == 'Bronze', 'points'] = 1

In [41]:
#output 1

#aggregate
df_output_1 = df.groupby(['Team', 'Sport'])['points'].sum().reset_index()

#identify top sports per team
idx = df_output_1.groupby('Team')['points'].idxmax()
df_output_1.loc[idx]

             Team      Sport  points
0        Algorion  Athletics     7.0
5       Argentara     Hockey   116.0
11        Arkarus  Taekwondo     2.0
14       Arminius  Wrestling    10.0
30      Australis   Swimming   304.0
..            ...        ...     ...
734  Unitonaris-2     Tennis    14.0
740      Uzbarion  Wrestling    19.0
744      Venarion    Fencing     3.0
747     Vietarion   Shooting     5.0
749      Zimbaris   Swimming    15.0

[148 rows x 3 columns]

In [42]:
#create concatenated event and medal field
df_output_2 = df
df_output_2['results'] = df['Event'] + ' (' + df['Medal'] + ')'

In [43]:
#aggregate df, taking total points and a concatenated field with the events and medal results
df_output_2 = df_output_2.groupby(['Team', 'Name']).agg(
    points=('points', 'sum'),
    results=('results', lambda x: ', '.join(x))
).reset_index()

In [44]:
#output 2

#identify top athlete per team
idx = df_output_2.groupby('Team')['points'].idxmax()
df_output_2.loc[idx]

,Team,Name,points,results
2,Algorion,Sonia Short,7.0,"Athletics Men's 1,500 metres (Gold), Athletics..."
46,Argentara,Hannah Wilkins,6.0,"Football Men's Football (Gold), Football Men's..."
118,Arkarus,Phil Paterson,2.0,"Taekwondo Men's Flyweight (Bronze), Taekwondo ..."
120,Arminius,Anne Carr,4.0,"Wrestling Men's Heavyweight, Greco-Roman (Bron..."
321,Australis,John Manning,16.0,Swimming Women's 100 metres Breaststroke (Bron...
...,...,...,...,...
5943,Unitonaris-2,Gordon Campbell,4.0,"Tennis Mixed Doubles (Gold), Tennis Men's Doub..."
5952,Uzbarion,Anne Chapman,9.0,"Wrestling Men's Super-Heavyweight, Freestyle (..."
5974,Venarion,Piers Vance,3.0,"Fencing Men's epee, Individual (Gold)"
5979,Vietarion,Felicity Randall,5.0,"Shooting Men's Air Pistol, 10 metres (Gold), S..."
5980,Zimbaris,Jennifer Payne,15.0,Swimming Women's 100 metres Backstroke (Silver...