In [108]:
import pandas as pd

In [109]:
#create dataframes from CSVs
data_df = pd.read_csv('../data/challenge_8_point_of_sale.csv')
lookup_df = pd.read_csv('../data/challenge_8_lookup_table.csv')

In [110]:
#convert string to date, filter to relevant dates
data_df['Date'] = pd.to_datetime(data_df['Date'])
data_df = data_df[data_df['Date'] >= pd.to_datetime('2013-07-01')]

In [111]:
#join data with lookup table
df = pd.merge(data_df, lookup_df, how='inner', on='Desc')
df.head()

   TicketID       Date  MemberID                     Desc  Price   Type
0    102398 2013-07-01       NaN  House Made Potato Chips    3.0   Side
1    102398 2013-07-01       NaN              Onion Rings    7.0   Side
2    102398 2013-07-01       NaN    Soup of the Day - Cup    3.0   Soup
3    102398 2013-07-01       NaN   Soup of the Day - Bowl    5.0   Soup
4    102398 2013-07-01       NaN       House Salad - Half    3.0  Salad

In [112]:
#concatenate all items per order
df = df.groupby('TicketID')['Type'].agg('|'.join).reset_index()
df.head()

   TicketID                                               Type
0    102398  Side|Side|Soup|Soup|Salad|Pizza|Pizza|Pizza|Pi...
1    102415  Side|Soup|Salad|Salad|Salad|Salad|Pizza|Pizza|...
2    102418                                   Soup|Salad|Drink
3    102424  Side|Side|Salad|Burger|Salad|Pizza|Pizza|Drink...
4    102433  Side|Side|Soup|Salad|Pizza|Pizza|Pizza|Pizza|P...

In [113]:
#create a filtered df with only meal deal eligible orders
meal_deal_df = df[((df['Type'].str.contains('Pizza')) | (df['Type'].str.contains('Burger'))) & (df['Type'].str.contains('Side')) & (df['Type'].str.contains('Drink'))]

In [114]:
#count total orders and those eligible for the meal offer
total_count = len(df)
meal_deal_count = len(meal_deal_df)

In [115]:
#calculate pct of orders eligible for meal deal
meal_deal_count / total_count

0.7074917726011486