In [31]:
import pandas as pd

In [32]:
df = pd.read_csv('../data/challenge_438.csv')

df.head()

,Subgroup Name,Order,Currency,2022-12-30,2023-01-25,2023-01-03,2023-01-29,2022-12-02,2022-12-17,2022-12-03,...,2023-01-18,2023-01-16,2023-01-17,2023-01-19,2023-01-20,2023-01-21,2023-01-24,2023-01-26,2023-01-27,2023-01-28
0,XXX,7,JPY,1310439.09,469928.83,1328172.78,1763119.10,2098946.51,1620981.80,2098946.51,...,1814876.00,1817752.55,1790166.91,1184013.94,1045575.92,1045575.92,165975.04,1717233.73,1763119.10,1763119.10
1,XXX,3,CHF,5559135.08,5493002.12,5570408.45,5478855.71,5535687.35,5520497.86,5535687.35,...,5553343.69,5482472.28,5516953.39,5521213.03,5483929.99,5483929.99,5480296.04,5478610.44,5478855.71,5478855.71
2,XXX,8,NOK,98930.30,96329.87,97967.24,96988.68,100892.42,99082.85,100892.42,...,97177.10,97159.05,97716.00,97177.10,97236.41,97236.41,97035.76,96870.98,96988.68,96988.68
3,XXX,10,SGD,4893866.43,4898639.71,4967975.95,4923037.73,4937097.38,4889305.90,4937097.38,...,4935466.67,4929849.68,4928374.27,4906880.60,4904370.59,4904370.59,4903197.17,4929147.98,4923037.73,4923037.73
4,XXX,6,HKD,1208399.57,1180435.25,1222643.50,1185579.83,1229902.55,1222922.13,1229902.55,...,1194336.16,1194246.35,1195749.22,1189913.67,1186676.79,1186676.79,1183760.68,1183415.64,1185579.83,1185579.83

In [33]:
# unpivot to put the dates into a column. convert it to a date and sort on it

df = pd.melt(df, id_vars=['Subgroup Name', 'Order', 'Currency'])
df['variable'] = pd.to_datetime(df['variable'])

df = df.sort_values(['Order', 'variable'])

df.head()

    Subgroup Name  Order Currency   variable       value
57            XXX      1      AUD 2022-12-02  2463704.27
83            XXX      1      AUD 2022-12-03  2463704.27
109           XXX      1      AUD 2022-12-04  2463704.27
122           XXX      1      AUD 2022-12-05  2417654.84
148           XXX      1      AUD 2022-12-06  2402520.03

In [34]:
# pivot so each date has its own column

df = df.pivot(columns=['variable'], values=['value'], index=['Subgroup Name', 'Order', 'Currency']).reset_index()

df

         Subgroup Name Order   Currency         value                \
variable           NaT   NaT        NaT    2022-12-02    2022-12-03
0                  XXX     1        AUD  2.463704e+06  2.463704e+06
1                  XXX     2        CAD  2.122770e+06  2.122770e+06
2                  XXX     3        CHF  5.535687e+06  5.535687e+06
3                  XXX     4        EUR  1.035696e+09  1.035696e+09
4                  XXX     5        GBP  7.583115e+08  7.583115e+08
5                  XXX     6        HKD  1.229903e+06  1.229903e+06
6                  XXX     7        JPY  2.098947e+06  2.098947e+06
7                  XXX     8        NOK  1.008924e+05  1.008924e+05
8                  XXX     9        SEK  6.465366e+05  6.465366e+05
9                  XXX    10        SGD  4.937097e+06  4.937097e+06
10                 XXX    11        USD  2.023533e+09  2.023533e+09
11                 XXX    12        ZAR  2.614020e+03  2.614020e+03
12                 XXX    13  Total cve  3.836679e+09  3.836679e+09

                                                                  \
variable    2022-12-04    2022-12-05    2022-12-06    2022-12-07
0         2.463704e+06  2.417655e+06  2.402520e+06  2.422793e+06
1         2.122770e+06  2.005153e+06  1.974667e+06  1.974145e+06
2         5.535687e+06  5.515913e+06  5.524623e+06  5.516353e+06
3         1.035696e+09  1.015775e+09  1.016543e+09  1.012579e+09
4         7.583115e+08  7.543718e+08  5.225553e+08  8.103950e+08
5         1.229903e+06  1.236850e+06  1.239815e+06  1.230768e+06
6         2.098947e+06  1.084926e+06  2.075634e+04  5.954606e+05
7         1.008924e+05  9.952621e+04  9.905464e+04  9.876874e+04
8         6.465366e+05  6.439339e+05  6.444769e+05  6.453327e+05
9         4.937097e+06  4.969645e+06  4.952567e+06  4.921580e+06
10        2.023533e+09  2.031831e+09  2.323977e+09  2.313101e+09
11        2.614020e+03  2.645920e+03  2.662470e+03  2.667980e+03
12        3.836679e+09  3.819955e+09  3.879937e+09  4.153483e+09

                        ...                                            \
variable    2022-12-08  ...    2023-01-21    2023-01-22    2023-01-23
0         2.417712e+06  ...  2.411359e+06  2.411359e+06  2.423831e+06
1         2.014865e+06  ...  2.515689e+06  2.515689e+06  2.528163e+06
2         5.513333e+06  ...  5.483930e+06  5.483930e+06  5.474015e+06
3         1.016183e+09  ...  1.007904e+09  1.007904e+09  1.164691e+09
4         8.087263e+08  ...  1.569755e+07  1.569755e+07  1.569664e+07
5         1.226519e+06  ...  1.186677e+06  1.186677e+06  1.186747e+06
6         1.686819e+06  ...  1.045576e+06  1.045576e+06  1.107835e+06
7         9.884481e+04  ...  9.723641e+04  9.723641e+04  9.751928e+04
8         6.447168e+05  ...  6.307941e+05  6.307941e+05  6.323263e+05
9         4.909043e+06  ...  4.904371e+06  4.904371e+06  4.915460e+06
10        2.303075e+09  ...  1.083024e+09  1.083024e+09  1.266657e+09
11        2.660790e+03  ...  2.600700e+03  2.600700e+03  2.595200e+03
12        4.146499e+09  ...  2.124904e+09  2.124904e+09  2.465414e+09

                                                                  \
variable    2023-01-24    2023-01-25    2023-01-26    2023-01-27
0         2.412697e+06  2.421401e+06  2.430967e+06  2.432361e+06
1         2.536008e+06  2.483608e+06  2.461185e+06  2.474172e+06
2         5.480296e+06  5.493002e+06  5.478610e+06  5.478856e+06
3         1.016248e+09  1.015132e+09  1.023924e+09  1.015807e+09
4         1.563268e+07  1.563967e+07  1.565812e+07  1.564485e+07
5         1.183761e+06  1.180435e+06  1.183416e+06  1.185580e+06
6         1.659750e+05  4.699288e+05  1.717234e+06  1.763119e+06
7         9.703576e+04  9.632987e+04  9.687098e+04  9.698868e+04
8         6.343809e+05  6.313528e+05  6.298066e+05  6.286157e+05
9         4.903197e+06  4.898640e+06  4.929148e+06  4.923038e+06
10        1.400655e+09  1.396840e+09  1.400338e+09  1.402597e+09
11        2.581810e+03  2.580640e+03  2.579600e+03  2.585050e+03
12        2.449951e+09  2.445289e+09  2.458850e+09  2.453033e+09


variable    2023-01-28    2023-01-29    2023-01-30
0         2.432361e+06  2.432361e+06  2.408007e+06
1         2.474172e+06  2.474172e+06  2.463845e+06
2         5.478856e+06  5.478856e+06  5.469242e+06
3         1.015807e+09  1.015807e+09  1.017932e+09
4         1.564485e+07  1.564485e+07  1.563593e+07
5         1.185580e+06  1.185580e+06  1.187478e+06
6         1.763119e+06  1.763119e+06  1.544514e+06
7         9.698868e+04  9.698868e+04  9.622983e+04
8         6.286157e+05  6.286157e+05  6.293849e+05
9         4.923038e+06  4.923038e+06  4.938886e+06
10        1.402597e+09  1.402597e+09  1.131268e+09
11        2.585050e+03  2.585050e+03  2.569580e+03
12        2.453033e+09  2.453033e+09  2.183576e+09

[13 rows x 63 columns]