In [90]:
import pandas as pd

In [91]:
df = pd.read_csv('../data/challenge_442.csv')

df.head()

,play_id,game_id,home_team,away_team,possession_team,game_date,time,yrdln,desc,play_type,yards_gained
0,46,2009091000,PIT,TEN,PIT,2009-09-10,15:00,TEN 30,R.Bironas kicks 67 yards from TEN 30 to PIT 3....,kickoff,0.0
1,68,2009091000,PIT,TEN,PIT,2009-09-10,14:53,PIT 42,(14:53) B.Roethlisberger pass short left to H....,pass,5.0
2,92,2009091000,PIT,TEN,PIT,2009-09-10,14:16,PIT 47,(14:16) W.Parker right end to PIT 44 for -3 ya...,run,-3.0
3,113,2009091000,PIT,TEN,PIT,2009-09-10,13:35,PIT 44,(13:35) (Shotgun) B.Roethlisberger pass incomp...,pass,0.0
4,139,2009091000,PIT,TEN,PIT,2009-09-10,13:27,PIT 44,(13:27) (Punt formation) D.Sepulveda punts 54 ...,punt,0.0

In [92]:
# Output 1: calculate the yards gained by pass and run each year and the pct of total yards that came from runs

df = df.query('play_type in ("run", "pass")')
df['year'] = df['game_date'].apply(lambda x: x[:4])

df_1 = df.groupby(['year', 'play_type'])['yards_gained'].sum().reset_index()
df_1 = pd.pivot(df_1, index='year', columns='play_type', values='yards_gained').reset_index()

df_1['pct run'] = round((df_1['run'] / (df_1['pass'] + df_1['run'])) * 100, 2)

df_1.head()

play_type  year      pass      run  pct run
0          2009  105629.0  56062.0    34.67
1          2010  113251.0  59422.0    34.41
2          2011  116813.0  60060.0    33.96
3          2012  125637.0  63464.0    33.56
4          2013  119526.0  57762.0    32.58

In [93]:
# Output 2: identify the 3 teams that have relied most heavily on the run game

df_2 = df[df['play_type'] == 'run'].groupby('possession_team')['play_type'].count().reset_index(name='count_run_plays')

df_2.sort_values('count_run_plays', ascending=False).reset_index()[:3]

   index possession_team  count_run_plays
0     24             NYJ             4665
1      4             CAR             4551
2     12             HOU             4545