In [40]:
import pandas as pd

In [41]:
df = pd.read_csv('../data/challenge_390.csv')
df.head()

,Match_ID,Player_Name,Team,Opposition,Runs,NotOut,Mins,BF,4s,6s,SR,Inns,Ground,Start Date,Match_Winner,Margin
0,T20I # 1652,RW Chakabva,Zimbabwe,U.S.A.,31,0.0,-,23,4,1,134.78,1,Bulawayo,14-Jul-22,Zimbabwe,46 runs
1,T20I # 1652,CR Ervine,Zimbabwe,U.S.A.,11,0.0,-,9,2,0,122.22,1,Bulawayo,14-Jul-22,Zimbabwe,46 runs
2,T20I # 1652,SC Williams,Zimbabwe,U.S.A.,37,0.0,-,35,3,0,105.71,1,Bulawayo,14-Jul-22,Zimbabwe,46 runs
3,T20I # 1652,I Kaia,Zimbabwe,U.S.A.,2,0.0,-,5,0,0,40,1,Bulawayo,14-Jul-22,Zimbabwe,46 runs
4,T20I # 1652,Sikandar Raza,Zimbabwe,U.S.A.,82*,1.0,-,40,7,5,205,1,Bulawayo,14-Jul-22,Zimbabwe,46 runs

In [42]:
#filter to USA
df = df[df['Team'] == 'U.S.A.']

In [43]:
#replace non-numeric characters and convert to a numeric column
df['runs_parsed'] = pd.to_numeric(df['Runs'].str.replace('[^0-9]', '', regex=True))

In [ ]:
#count the number of runs per player
df = df.groupby('Player_Name')['runs_parsed'].agg('sum').reset_index()

In [ ]:
#take the top 5 players by runs scored
df.sort_values('runs_parsed', ascending=False)[:5]

    Player_Name  runs_parsed
21    SR Taylor        540.0
0   Aaron Jones        266.0
9   JS Malhotra        246.0
13     MD Patel        235.0
26  XM Marshall        204.0