In [101]:
import pandas as pd

In [102]:
df = pd.read_csv('../data/challenge_422.csv')

df.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
0,1849-01-01,26.704,1.435,Abidjan,Cote d'Ivoire,5.63N,3.23W
1,1849-02-01,27.434,1.362,Abidjan,Cote d'Ivoire,5.63N,3.23W
2,1849-03-01,28.101,1.612,Abidjan,Cote d'Ivoire,5.63N,3.23W
3,1849-04-01,26.140,1.387,Abidjan,Cote d'Ivoire,5.63N,3.23W
4,1849-05-01,25.427,1.200,Abidjan,Cote d'Ivoire,5.63N,3.23W

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 239177 entries, 0 to 239176
Data columns (total 7 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   dt                             239177 non-null  str
 1   AverageTemperature             228175 non-null  float64
 2   AverageTemperatureUncertainty  228175 non-null  float64
 3   City                           239177 non-null  str
 4   Country                        239177 non-null  str
 5   Latitude                       239177 non-null  str
 6   Longitude                      239177 non-null  str
dtypes: float64(2), str(5)
memory usage: 12.8 MB

In [104]:
# filter to relevant data

df['dt'] = pd.to_datetime(df['dt'], format='%Y-%m-%d')
df = df[df['dt'] >= '1950-01-01']

df.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,City,Country,Latitude,Longitude
1212,1950-01-01,26.773,0.239,Abidjan,Cote d'Ivoire,5.63N,3.23W
1213,1950-02-01,27.527,0.348,Abidjan,Cote d'Ivoire,5.63N,3.23W
1214,1950-03-01,28.344,0.431,Abidjan,Cote d'Ivoire,5.63N,3.23W
1215,1950-04-01,27.830,0.467,Abidjan,Cote d'Ivoire,5.63N,3.23W
1216,1950-05-01,26.896,0.248,Abidjan,Cote d'Ivoire,5.63N,3.23W

In [105]:
# Output 1: Cities with avg temperatures >= 25

df_agg = df.groupby(['City', 'Country'])['AverageTemperature'].mean().reset_index()
df_agg = df_agg[df_agg['AverageTemperature'] >= 25]

df_agg.head()

         City        Country  AverageTemperature
0     Abidjan  Cote d'Ivoire           26.518292
2   Ahmadabad          India           26.982792
7   Bangalore          India           25.290026
8     Bangkok       Thailand           27.633291
12     Bombay          India           27.066308

In [106]:
# Output 2: Counting the country with the most cities in the above output

df_agg['Count'] = df_agg.groupby('Country')['City'].transform('count')
idx = df_agg['Count'].idxmax()

df_agg.loc[idx].to_frame().T[['Country', 'Count']]

  Country Count
2   India    14

In [107]:
# Output 3: Years with the highest and lowest avg temp

df['Year'] = df['dt'].dt.year
df = df.groupby('Year')['AverageTemperature'].mean().reset_index()

idx_1 = df['AverageTemperature'].idxmin()
idx_2 = df['AverageTemperature'].idxmax()

print('Lowest:')
print(df.loc[idx_1].to_frame().T)
print('\nHighest:')
print(df.loc[idx_2].to_frame().T)

Lowest:
     Year  AverageTemperature
6  1956.0           18.480926

Highest:
      Year  AverageTemperature
63  2013.0           20.263006