In [72]:
import pandas as pd

In [73]:
# create dataframe for starting data

data = []

for i in range(1, 1001):
    dict = {}
    dict['locker'] = i
    dict['position'] = 0
    data.append(dict)

df = pd.DataFrame(data)
df.head()

   locker  position
0       1         0
1       2         0
2       3         0
3       4         0
4       5         0

In [74]:
for student in range(1, 1001):
    for i in range(0, 1000):
        if round(df.loc[i, 'locker'] / student) == (df.loc[i, 'locker'] / student):
            df.loc[i, 'position'] = df.loc[i, 'position'] + 1

In [75]:
for i in range(1000):
    if round(df.loc[i, 'position'] / 2) == (df.loc[i, 'position'] / 2):
        df.loc[i, 'pos'] = 'Closed'
    else:
        df.loc[i, 'pos'] = 'Open'

In [ ]:
df = df[df['pos'] == 'Open']
df.head()

    locker  position   pos
0        1         1  Open
3        4         3  Open
8        9         3  Open
15      16         5  Open
24      25         3  Open