In [ ]:
import pandas as pd

In [ ]:
# create df

data = [
    {'employee': 'Analyst', 'id': 3, 'man_id': 2},
    {'employee': 'Manager', 'id': 2, 'man_id': 1},
    {'employee': 'Director', 'id': 1, 'man_id': 4},
    {'employee': 'Vice President', 'id': 4, 'man_id': 5},
    {'employee': 'CEO', 'id': 5,}
]

df = pd.DataFrame(data)

df

         employee  id  man_id
0         Analyst   3     2.0
1         Manager   2     1.0
2        Director   1     4.0
3  Vice President   4     5.0
4             CEO   5     NaN

In [ ]:
results = []
count = 1
working_df = df.rename(columns={'employee': 'w_employee', 'id': 'w_id', 'man_id': 'w_man_id'})

while True:
    # join to climb to the next level of the hierarchy
    working_df = pd.merge(working_df, df, how='inner', left_on='w_man_id', right_on='id')
    
    # add the joined records to the result. they'll be unioned later
    result = working_df.rename(columns={'employee': 'manager', 'w_employee': 'employee'})[['employee', 'manager']]
    result['hierarchy'] = count
    results.append(result)

    # replace employee info with manager info to loop through again
    working_df = working_df[['w_employee', 'w_man_id', 'man_id']].rename(columns={'w_man_id': 'w_id', 'man_id': 'w_man_id'})

    # break the loop when there are no records remaining. at that point, everyone has reached the top of the hierarchy
    if len(working_df) == 0:
        break

    count += 1

In [ ]:
# union results into one df

final_df = pd.concat(results, axis=0)

final_df.sort_values(['employee', 'hierarchy'])

         employee         manager  hierarchy
0         Analyst         Manager          1
0         Analyst        Director          2
0         Analyst  Vice President          3
0         Analyst             CEO          4
2        Director  Vice President          1
2        Director             CEO          2
1         Manager        Director          1
1         Manager  Vice President          2
1         Manager             CEO          3
3  Vice President             CEO          1